server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/   # 单机版
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  # 集群版

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000



feign:
  hystrix:
    enabled: true  # 开启feign熔断

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #这里设置理想的超时时间，如下5000ms，解决feign的默认1秒超时
            # 这里的超时时间会覆盖 @HystrixCommand 注解里设置的熔断时间
            timeoutInMilliseconds: 5000


